name: MCChess
version: '1.0'
main: me.kihei.mcchess.MCChess
api-version: '1.20'
commands:
  blockRestore:
    description: Toggles system to place back chess blocks.
    usage: /<command>
    permission: mcchess.blockrestore
  white:
    description: Set the player playing the white pieces.
    usage: /<command> [name]
  black:
    description: Set the player playing the black pieces.
    usage: /<command> [name]
  players:
    description: View the players playing the white and black pieces.
    usage: /<command>
  clock:
    description: Set chess clock.
    usage: /<command> [time control]
    permission: mcchess.clock
  resetClock:
    description: Reset the chess clock.
    usage: /<command>
    permission: mcchess.resetclock
  reset:
    description: Reset the game.
    usage: /<command>
    permission: mcchess.reset
  fly:
    description: Fly.
    usage: /<command>
    permission: mcchess.fly
  speed:
    description: Set walk/fly speed.
    usage: /<command> [speed]
    permission: mcchess.speed
  resign:
    description: Resign the chess game.
    usage: /<command>
  getfen:
    description: Gets the chess board's FEN code to copy to clipboard.
    usage: /<command>
  loadfen:
    description: Loads a FEN code to the chess board.
    usage: /<command> [FEN]
    permission: mcchess.loadfen